### ISSUE TITLE
Need example: Pass multiple data properties and all data from main template

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-child-templates#4]
1. How can I pass all data from main template to child template?
2. How can I pick several objects from main template data and pass it to child template? 

Example (main template data):

```
{
  title: 'Name of the report',
  description: 'Long description',
  rows: [ 
    [1, "two", 3].
    [4. "five", six]
  ]
}
```

In case 2 I change a child that needs only title and description?

**Comment by pofider** [comment]
1: Is now in docs:

> The root request input data cascade through child templates, but you can also pass additional data to the child template through its declaration
> 
> ``` html
> {#child myChildTemplate @data.paramA=foo}
> ```

2: This is missing and you cannot pass additional complex objects into child templates. The missing feature is here https://github.com/jsreport/jsreport-child-templates/issues/1
You can workaround it with script, but this one should be quickly fixed, I've it somewhere already implemented.
