### ISSUE TITLE
Child templates recursion

### ISSUE THREAD

**Issue by andyheyns93** [jsreport/jsreport-child-templates#8]
I have a problem using child templates.

`Error: Render cycle detected. Template at /child was rendered previously in this render request (hierarchy: /template -> /child -> /child). Please verify that reporter.render is not causing cycle
    at module.exports (/app/node_modules/jsreport-core/lib/util/createError.js:11:13)
    at Reporter.createError (/app/node_modules/jsreport-core/lib/reporter.js:332:12)
    at AsyncFunction.<anonymous> (/app/node_modules/jsreport-templates/lib/templates.js:157:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

In my real life situation I have a list of objects which is maybe nested 5x deep. That's why I needed recursion to create this template. The use of 'foreach' functions isn't a proper solution because I don't know when the nesting stops.

If you have a workaround or can create a fix for the 'Render Cycle', let me know.

I don't know if it helps but can't there be a hash check on the data which is given to the child template?

https://github.com/jsreport/jsreport-templates/blob/master/lib/templates.js#L145

Ex: if the data is the same, still produce the error and when it's a different hash, render the template?

Thanks in advance

Playground example:
https://playground.jsreport.net/w/anon/x~Y~sQVq

Note: maybe wrong repo can also be posted here: https://github.com/jsreport/jsreport-templates

**Comment by pofider** [comment]
Thank you for the very nice description including the demo.

I found out this is actually already reported here - https://github.com/jsreport/jsreport/issues/780
Please check it out.
